import html
import re
import unicodedata


def clean_markdown(markdown: str) -> str:
    """
    Perform lightweight normalization on Markdown generated by edgartools.

    The goal is NOT to modify document structure.
    Only remove formatting artifacts while preserving semantic meaning.
    """

    markdown = html.unescape(markdown)

    markdown = unicodedata.normalize("NFKC", markdown)

    markdown = markdown.replace("\u00A0", " ")

    lines = [line.rstrip() for line in markdown.splitlines()]

    markdown = "\n".join(lines)

    markdown = re.sub(r"\n{3,}", "\n\n", markdown)

    return markdown.strip()